[package]
name = "white_box_ai"
version = "1.0.0"
authors = ["Vishal"]
edition = "2018"


[dependencies]
rand = "0.8.3"
ndarray = "0.15.2"
ndarray-rand = "0.14.0"
itertools = "0.8.0"
ndarray-csv = "0.5.1"
csv = "^1"
